import "@/app/globals.css";

import Header from "@/app/components/header";
import Footer from "@/app/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  teste: "teste metadata",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className="flex flex-col h-screen antialiased">
        <Header />
        <main className="xl:w-7xl w-auto flex-1 my-10">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
